apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these lables belongs to replicaset resources
  labels:
    component: backend
    project: expense
    tier: app
    # how many replicas required
spec:
  replicas: {{ .Values.deployment.replicas }}
  # which pod you want replica
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
# pod definition
  template:
    metadata:
    # selector labels must match below labels
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: joindevops/backend: {{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
           name: backend